pipeline {
    agent any

    tools {
        python 'Python3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'ae1932ed-f1e2-4923-87af-0a6440dc621a',
                    url: 'https://github.com/ebaah2942/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh '''
                    . venv/bin/activate
                    pytest --junitxml=report.xml
                    '''
                }
            }
            post {
                always {
                    dir('messaging_app') {
                        junit 'report.xml'
                    }
                }
            }
        }
    }
}
