#!/bin/bash
set -e

# Deploy Blue version (current)
kubectl apply -f blue_deployment.yaml

# Deploy Green version (new)
kubectl apply -f green_deployment.yaml

# Apply the shared service
kubectl apply -f kubeservice.yaml

echo "✅ Blue and Green deployments applied."

# Check pods
kubectl get pods -l app=messaging-app

# Tail logs of Green pods to check for errors
GREEN_POD=$(kubectl get pods -l app=messaging-app -o name | grep green | head -n 1)
kubectl logs -f $GREEN_POD
